### ISSUE TITLE
universal material structure 

### ISSUE THREAD

**Issue by malkosh** [vizoogmbh/u3m#5]
limiting u3m to just visual data is going to only add more issues later. Here is the proposed structure. These can change but at least the major categories are set.

1. visual properties
2. physical properties
3. material information
4. custom
   1. visual properties
   1. physical properties
   1. material information
   1. additional

**Comment by malkosh** [comment]
And here is the proposed material information we are interested in saving. Items that state multiple can have multiple entries

1. composition
   1. raw material
      1. raw material
      1. ratio
      1. country of origin

**Comment by vizoomartin** [comment]
Hi Yazan, i have a few questions/remarks:
- **4.custom**: This whole point of this section is that it's not structured/defined, so everybody can input their own information, in their own space (e.g. "vizoo":, "swatchbook":...) without risk of the databeing overridden by another application. If we again define input areas (visual, physical, material, additional), this custom specific safe guard will be lost. Everybody could place their specific space in each section, but i dont see the benefit in comparison to the current implementation?
- **3.1.i.b supplier ID**: How can this work? IDs are specific for each brand or plm/dbsystem, and should not be part of the **interoperable** u3m. 

As discussed before, we are hesitant to add dynamic information (price, lead times, dimensions, minimum order etc) to a file that can exist disconnected from this information, as the information will not be reliable. 
**PLM InfoI** think we have to decide whether u3m includes PLM information (like in your suggestion) or, is an addition to the PLM data for a full material. Again, we should address the concern above though if PLM data makes sense outside of the PLM system. 
**Confidentiality**: part of the suggested info is probably confidential for each company (price, lead time, minimum order, names etc). If that's the case, the materials can also only be distributed inside the company, instead of e.g. from supplier to several companies. 

Nevertheless, it does make sense to include data to categorize/search/filter the materials.
Proposal to add to "material":

```
"material":{
...
 "color":{
  "RGB":"",
  "LAB":"",
  ...
 },
 "physics":{
  "mass":100 //(e.g. g/m²)
  "thickness":1 //(mm)
 },
 "supplier":[ //list
  "name":"",
  "country":""
 ],
"composition":[ //list
  "raw_material":"",
  "percent":"" //(%)
 ],
 "contruction/contructiontype":"" //that could be very helpful to categorize, maybe as a list?
}
```

**Comment by ReinhardOnVizoo3d** [comment]
I agree that "dynamic" data should not be part of u3m.
_Supplier id_ however is not dynamic and can be part of u3m in my view. Just we should clarify exactly for each item what it means. In case of _Supplier id_, does it mean the id of the supplier or the supplier internal material id? 
Generally I see no reason not to add such "PLM information".

**Comment by malkosh** [comment]
dynamic data can be under custom I would argue however that there is a difference between set custom data and dynamic one. for example.
pricing can have 
set public data
and negotiated dynamic price

At that point in terms of confidentiality, the software system should be the one taking care of what data to contain or not otherwise even if the confidential data is under custom, it can still be shared. so the responsibility is on the user and the software

supplier data is a must. supplier ID certainly can be per client but again two different fields
supplier Name set
supplier internal ID dynamic or custom

but I still think the data structure can at least be organized by type not by vendor, otherwise this is less of a standard and more of catchall. if that makes sense

**Comment by malkosh** [comment]
plus the moment you put it under material information, it leaves your space alone, it doesn't touch physics or visuals. it's already in a separate space. and IF vendors need a dedicated space, they can go under additional.

**Comment by vizoomartin** [comment]
Please see the draft in the upcoming U3M newsletter, lets use this as basis for discussion
